"""Generate test cases from a user story with an LLM.

    python -m ai.generate_test_cases docs/user-stories/checkout.md
    python -m ai.generate_test_cases --story "As a shopper I want to remove items from my cart..."

Output is saved to docs/generated/ for a human to REVIEW before use.
"""
import argparse
import datetime
from pathlib import Path

from ai.llm_client import PROVIDER, ask_llm, load_prompt


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("story_file", nargs="?", help="Markdown file containing the user story")
    parser.add_argument("--story", help="User story text (instead of a file)")
    args = parser.parse_args()
    story = args.story or Path(args.story_file).read_text(encoding="utf-8")

    answer = ask_llm(load_prompt("test_cases", story=story))

    out_dir = Path("docs/generated"); out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    out = out_dir / f"test-cases-{stamp}.md"
    out.write_text(f"<!-- Generated by {PROVIDER}. Review before use. -->\n\n{answer}\n", encoding="utf-8")
    print(f"Saved {out}. Review it, fix mistakes, then move good cases into the suite.")


if __name__ == "__main__":
    main()
